build-prod-image:
  extends: .base-script
  variables:
    channel: Prod
  services:
    - docker:dind
  stage: build
  image: public.ecr.aws/g4a0y2u8/node-awscli-docker:latest-v20
  script:
    - node -v
    - ( cd packages/store && npm ci && npm run build-ci )

    - while true; do sleep 1 && echo "try docker info" && docker info && break; done

    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ECR_URL
    - docker build  --build-arg CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID --build-arg BUILD_ID=$CI_PIPELINE_ID  -f ./Dockerfile -t $IMAGE_NAME_PROD .  | cat
    - docker tag $IMAGE_NAME_PROD $AWS_ECR_URL/$IMAGE_NAME_PROD:$IMAGE_TAG_ID
    - docker push $AWS_ECR_URL/$IMAGE_NAME_PROD:$IMAGE_TAG_ID | cat
    - curl --insecure --user project115:ch1u6dy8zyiuasdb --data-urlencode "projectId=115"  --data-urlencode "title=$CI_COMMIT_TITLE" --data-urlencode "message=$CI_COMMIT_MESSAGE" "https://api.nanoheal.work/versions/update?channel=$channel&name=$CI_COMMIT_BRANCH&build=$CI_PIPELINE_ID&image=$PROJECT_IMAGE_NAME&url=$AWS_ECR_URL/$IMAGE_NAME_PROD:$IMAGE_TAG_ID"  2>&1
    # - curl --insecure --user cicd:REpfyr20vQVcULddTnFKg --data-urlencode "title=$CI_COMMIT_TITLE" --data-urlencode "message=$CI_COMMIT_MESSAGE" "https://api.nanoheal.site/versions/update?channel=$channel&name=$CI_COMMIT_BRANCH&build=$CI_PIPELINE_ID&image=$PROJECT_IMAGE_NAME&url=$AWS_ECR_URL/$IMAGE_NAME_PROD:$IMAGE_TAG_ID"  2>&1
